# --- CLOUD POSTGRESQL (NEON) ---
# Add "jdbc:" to the start of your connection string
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_2UTbYB4ynMFQ@ep-summer-heart-an1v3kav.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2UTbYB4ynMFQ

# --- HIBERNATE & INIT SETTINGS ---
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# This ensures your menu items from data.sql are inserted into the new cloud DB
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true